# Generated by Django 3.1.2 on 2020-10-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20201006_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id_gender',
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='discipline',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='record',
            field=models.IntegerField(primary_key='true', serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='secondName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='telephone',
            field=models.CharField(max_length=11),
        ),
    ]
